config/routes.rb
Rails.application.routes.draw do


  get 'oauths/oauth'

  get 'oauths/callback'

  # get 'email/index'


  root 'users#index'
  resources :users
  # , except: [:show, :edit]
  get 'user_profile' => 'users#show'
  get 'edit_user' => 'users#edit'


  resources :weather_reports
  resources :user_sessions
  resources :twitter
  resources :instagram
  resources :facebook

  #get '/auth/:provider/callback', to: 'user_sessions#create'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
 # attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  require 'google/api_client'

  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

  has_many :authentications, dependent: :destroy


  def twitter_client
    twitter_authentication = self.authentications.find_by_provider("twitter")
    if twitter_authentication
      twitter_api_client = Twitter::REST::Client.new do |config|
        config.consumer_key = Figaro.env.tw_consumer_key
        config.consumer_secret = Figaro.env.tw_consumer_secret
        config.access_token = twitter_authentication.access_token
        config.access_token_secret = twitter_authentication.access_secret
      end
      return twitter_api_client
    end
  end


  def facebook_client
    facebook_authentication = self.authentications.find_by_provider("facebook")
    if facebook_authentication
      facebook_api_client = Koala::Facebook::API.new(facebook_authentication.access_token)
      return facebook_api_client
    end
  end

  def google_authentication
    authentications.find_by_provider("google")
  end

def google_client
    # Application name is what you named it in Google Developer Console
    google_api_client = Google::APIClient.new({
      application_name: 'The Hub'
    })
    google_api_client.authorization = Signet::OAuth2::Client.new({
      client_id: Rails.application.secrets.google_consumer_key,
      client_secret: Rails.application.secrets.google_consumer_secret,
      access_token: google_authentication.access_token
    })
    return google_api_client
  end

  def gmail_threads
    client = google_client
    gmail_api = client.discovered_api('gmail', 'v1')
    results = client.execute!(
      :api_method => gmail_api.users.threads.list,
      :parameters => { :userId => 'me' })
    threads = results.data.threads
  end

  def gmail_message(id_number)
    client = google_client
    gmail_api = client.discovered_api('gmail', 'v1')
    batch_results = []

    batch = Google::APIClient::BatchRequest.new do |result|
      batch_results << result
    end

    @gmail_messages = id_number.map do |value|
      batch.add(api_method: gmail_api.users.threads.get, parameters: { :userId => 'me', :id => value })
    end
    client.execute(batch)

    @gmail_messages = batch_results

    @gmail_messages.map do |item|
      item.data.messages[0]
    end
  end

end

app/models/weather_report.rb
require "open-uri"
require "json"


class WeatherReport
  include HTTParty
  base_uri 'api.openweathermap.org/data/2.5'


  def initialize(city)
    @city = city
  end

  def city_name
    @city
  end

  def get_report
    @response = self.class.get("/weather?q=#{@city}&APPID=#{ENV["weather_key"]}")
  end

  def current_temp
     c_temp = @response['main']['temp']
     (c_temp - 273.15).ceil
  end

  def max_temp
     max_temp = @response['main']['temp_max']
     (max_temp - 273.15).ceil
  end

  def min_temp
     min_temp = @response['main']['temp_min']
     (min_temp - 273.15).ceil
  end

  def cloud_cover
    clouds = @response["clouds"]["all"]

    if (clouds < 30)
      return "sunny"
    elsif (30 >= clouds && clouds < 60)
      return "partially cloudy"
    else
      return "cloudy"
    end
  end

  def complete_info
    @response
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def not_authenticated
    redirect_to new_user_session_path, alert: "Please login first"
  end

end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController

 skip_before_filter :require_login

  def oauth
    login_at(params[:provider])
  end

  def callback

    add_provider_to_user(params[:provider])
    auth = current_user.authentications.find_by_provider(params[:provider])
    if auth
      auth.access_token = @access_token.token
      auth.access_secret = @access_token.secret if params[:provider] == "twitter"
      auth.save
      notice = "Linked up with #{params[:provider]}!"
    end
    redirect_to user_path(current_user), notice: notice
  end


  private

  def auth_params
    params.permit(:code, :provider)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create

    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to new_user_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, except: [:new, :create]

  def index
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save && login(user_params[:email], user_params[:password])
      redirect_to root_path
    else
      render :new
    end
  end

  def settings
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to user_profile_path
  end



  def show

    client = current_user.twitter_client
    if client
      @mentions = client.mentions_timeline
      @user_timeline = client.user_timeline
      @direct_messages = client.direct_messages
    end


    face_client = current_user.facebook_client
    if face_client
      @facebook_profile = face_client.get_object("me")
      # @feed = face_client.get_connections("me", "feed", "from")
      @feed = face_client.get_connection('me', 'posts',
                    { fields: ['message', 'id', 'from', 'type',
                                'picture', 'link', 'created_time', 'updated_time'
                        ]})
    end


    @weather_report = WeatherReport.new(current_user.city || 'San Fransisco')
    @weather_report.get_report

    if current_user.google_authentication
      @thread_id = []
      current_user.gmail_threads[0...20].each do |thread|
        @thread_id << thread.id
      end
    end

  end



  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weather_man_helper.rb
module WeatherManHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Hub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header>
  <div class="header">
    <h1>The Hub</h1>
  </div>
</header>


<body>

  <div class="content-container">
  <div class="notice">
     <%= flash[:notice] %>
  </div>
  <div class="alert">
     <%= flash[:alert] %>
  </div>
  <div>
   <% if current_user %>
        <%= link_to "Profile", user_profile_path %>
        <%= link_to 'Logout', user_session_path(current_user), method: :delete %>
        <%= link_to 'Settings', users_path %>
        <% else %>
      <%= link_to "Signup", new_user_path %> |
      <%= link_to "Login", new_user_session_path %>
  <% end %>
  </div>
  </div>
  <%= yield %>


</body>
</html>

app/views/oauths/callback.html.erb
<h1>Oauths#callback</h1>
<p>Find me in app/views/oauths/callback.html.erb</p>

app/views/oauths/oauth.html.erb
<h1>Oauths#oauth</h1>
<p>Find me in app/views/oauths/oauth.html.erb</p>

app/views/user_sessions/new.html.erb
<center><h1 class="log-in">Log In</h1>
  <div class="content-container">

      <%= form_tag user_sessions_path, :method => :post do %>

        <div class="field">
          <%= label_tag :email %><br />
          <%= text_field_tag :email %>
        </div>

        <div class="field">
          <%= label_tag :password %><br />
          <%= password_field_tag :password %>
        </div>

        <div class="actions">
          <%= submit_tag "Login" %>
        </div>
      <% end %>

      <p>Signup instead <%= link_to 'here', new_user_path %>
      </p>
  </div>
</center>

app/views/users/_city.html.erb
<%= form_for(@user) do |f| %>

<div class="field">
  <%= f.label :city %><br />
  <%= f.text_field :city %>
</div>

<div class="button">
  <%= f.submit %>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>

<br>

  <div class="button">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<p>
<%= render 'form' %>
</p>

app/views/users/index.html.erb
<center>
  <div class="header">
    <h1>Settings</h1>
  </div>
</center>

<div class="settings-box">
    <div class="settings">

       <!-- Radio button and label for #setting-content2 -->
       <input type="radio" name="settings" id="setting1" checked >
       <label for="setting1" class="bar">
           Authorization
       </label>

     <!-- Radio button and label for #setting-content1 -->

       <input type="radio" name="settings" id="setting2">
       <label for="setting2" class="bar">
           Account Info
       </label>


      <div id="setting-content1" class="setting-content">
        <p class="tweet"> <%= link_to 'Connect with Twitter', auth_at_provider_path(:provider => :twitter) %></p>
        <p class="tweet"><%= link_to 'Connect with Facebook', auth_at_provider_path(:provider => :facebook) %></p>
        <p class="tweet"><%= link_to 'Connect with Google', auth_at_provider_path(:provider => :google) %></p>
      </div>


      <div id="setting-content2" class="setting-content">
        <%= render "form" %>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<center><h1>Sign Up</h1>

<p>
<%= render "form" %>
</p>

<p> To login instead, click
<%= link_to 'here', new_user_session_path %>
</p>
</centre>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1">


<center>
  <div class="headings">
    <h4>
    Edit your information <b><i><%= link_to 'here', edit_user_path(current_user) %></i></b>
    </h4>
  </div>

</br>


  <div class="box">
    <div class="tabs">

       <!-- Radio button and label for #tab-content2 -->
       <input type="radio" name="tabs" id="tab1" checked >
       <label for="tab1">
           <i class="fa fa-twitter"></i><span>CSS3</span>
       </label>

     <!-- Radio button and label for #tab-content1 -->

       <input type="radio" name="tabs" id="tab2">
       <label for="tab2">
           <i class="fa fa-comment"></i><span>HTML5</span>
       </label>

       <!-- Radio button and label for #tab-content3 -->
       <input type="radio" name="tabs" id="tab3">
       <label for="tab3">
           <i class="fa fa-envelope"></i><span>jQuery</span>
       </label>


    <div id="tab-content1" class="tab-content">
      <p id="tweet"> <% if @user_timeline %>
            <% @user_timeline.each do |m| %>
              <ul class="message"><b><%="#{m.user.screen_name}:"%></b> <%="#{m.text}" %></ul>
          <% end %>
        <% end %>
      </p>
    </div>


    <div id="tab-content2" class="tab-content">
      <p id="tweet"><% if @mentions %>
              <% @mentions.each do |m| %>
                <ul class="message"><b><%="#{m.user.screen_name}:"%></b> <%="#{m.text}" %></ul>
            <% end %>
          <% end %>
      </p>
    </div>

    <div id="tab-content3" class="tab-content">
      <p id="tweet"> <% if @direct_messages %>
            <% @direct_messages.each do |m| %>
              <ul class="message"><b><%= "#{m.attrs[:sender_screen_name]}:"%></b> <%="#{m.text}"%></ul>
           <% end %>
          <% end %>
      </p>
    </div>
    </div>
  </div>

  <div class="box">
    <p><h3><u>Weather Report</u></h3></p>
    <h4>Weather in <%= @weather_report.city_name %></h4>

    <p>The current temperature is <b><%= @weather_report.current_temp %> C </b></p>
    <p>The high for today is <b><%= @weather_report.max_temp %> C </b></p>
    <p>The low for the day is <b><%= @weather_report.min_temp %> C </b></p>
    <p>It will be <b><%= @weather_report.cloud_cover %></b> today</p>
  </div>


  <div class="box">
    <p><h3><u>Facebook</u></h3></p>
    <% if @feed %>
      <% @feed.each do |item| %>
        <p><b><%= item["from"]["name"] %>:</b></p>
        <p><%= image_tag item["picture"] %></p>
        <p><%= item["message"]  %></p>

      <% end %>
    <% end %>
  </div>


  <div class="box">
    <div class="gmail">
      <label for="tab4", class="gmail">
        <i class="fa fa-envelope-o"></i><span>CSS3</span>
      </label>

      <div id="tab-content4" class="tab-content">
        <p id="tweet"> <% current_user.gmail_message(@thread_id).each do |option| %>
          <li class="message"> <%= link_to option.payload.headers.find { |header| header.name == 'From'}.value, "https://mail.google.com/mail/u/0/#inbox/#{option.id}", target: "_blank" %> </li>
          <% end %>
        </p>
      </div>

    </div>
  </div>

</center>






</html>

app/views/weather_reports/index.html.erb
<h1>Weather Report</h1>

<h3>Weather</h3>

<div class='report'>
<ul>
  <li>Current Temperature is <%= @weather_report.current_temp %> C </li>
  <li> High <%= @weather_report.max_temp %> C </li>
  <li> Low <%= @weather_report.min_temp %> C </li>
  <li>It wll be  <%= @weather_report.cloud_cover %> today</li>
</ul>
</div>